//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class practice
    {
        public long id { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Special Characters and Numbers are not allowed.")]
        public string name { get; set; }
        [Required]
        [Phone]
        [StringLength(10, MinimumLength = 10, ErrorMessage ="Phone number must be 10 digit.")]
        public string phone_number { get; set; }
        [Required]
        public string address { get; set; }
    }
}
